config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :lists do
    resources :items
  end

  get 'home/index'

  root to: 'home#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :items, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :lists, dependent: :destroy
  has_many :items, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  def role?(base_role)
    role == base_role.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end

  protected
 
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  respond_to :html, :js

  def create
    @list = List.find(params[:list_id])
    @item = @list.items.new(item_params)
    @item.user_id = current_user.id

    authorize @item
    if @item.save
      flash[:notice] = "List item was saved."
      redirect_to @list 
    else
      flash[:error] = "List item was not saved. Please try again."
      redirect_to @list 
    end
  end

  def destroy
    @list = List.find(params[:list_id])
    @item = @list.items.find(params[:id])

    authorize @item
    if @item.destroy
      flash[:notice] = "Successfully completed!"
    else
      flash[:error] = "There was an error. Please try again."
    end

    respond_with(@item) do |format|
      format.html { redirect_to @list }
    end
  end
  

  private

  def item_params
    params.require(:item).permit(:body)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = current_user.lists if current_user.present?
  end

  def show
    @list = List.find(params[:id])
    @items = @list.items
    authorize @list
  end

  def new
    @list = List.new
    authorize @list
  end

  def edit
    @list = List.find(params[:id])
    authorize @list
  end

  def create
    @list = current_user.lists.new(list_params)

    authorize @list
    if @list.save
      flash[:notice] = "List was saved."
      redirect_to @list
    else
      flash[:error] = "List was not saved. Please try again."
      render :new
    end
  end

  def update
    @list = List.find(params[:id])

    authorize @list
    if @list.update_attributes(list_params)
      flash[:notice] = "List was updated."
      redirect_to @list
    else
      flash[:error] = "List was not updated. Please try again."
      render :edit
    end
  end

  def destroy
    @list = List.find(params[:id])

    authorize @list
    if @list.destroy
      flash[:notice] = "List was deleted."
      redirect_to lists_path
    else
      flash[:error] = "List was not deleted. Please try again."
      render :show
    end
  end

  private

  def list_params
    params.require(:list).permit(:title, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/home/index.html.erb
<div class="span7 text-center">
<div class="jumbotron">
  <h1>BLOCITOFF</h1>
  <h4>a self-destructing to-do list</h4>
  <p>Complete your tasks in 7 days or they will automatically be deleted!</p>
  <div class="span7 text-center">
    <% if current_user.present? %>
      <%= link_to "My Lists", lists_path, class: 'btn btn-default btn-lg' %>
    <% else %>
      <%= link_to "Log In", new_user_session_path, class: 'btn btn-default btn-lg' %>
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-success btn-lg' %>
    <% end %>
  </div>
</div>
</div>

app/views/items/_form.html.erb
<% if current_user %>
  <%= form_for [@list, @list.items.new] do |f| %>
    <div class="form-group">
      <%= f.text_field :body, class: 'form-control', placeholder: "New list item" %>
    </div>
    <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
  <% end %>
<% end %>

app/views/items/_item.html.erb
<%= content_tag :div, id: "item-#{item.id}" do %>
  <% unless item.body.nil? %>
    <tr>
      <td><%= item.body %></td>
      <td><%= distance_of_time_in_words_to_now(item.created_at + 7.days) %></td>
      <td><%= link_to "Complete", [item.list, item], method: :delete, remote: true %></td>
    </tr>
  <% end %>
<% end %>

app/views/items/destroy.js.erb
<% if @item.destroyed? %>
  $('#item-'+<%=@item.id%>).hide();
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <div class="header">
      <div class="nav nav-tabs">
        <div class="pull-left nav-left">
          <%= link_to "Blocitoff", root_path %>
        </div>

        <div class="pull-right nav-right">
          <% if current_user %>
            Hello <%= current_user.name || current_user.email %>!
            <%= link_to "My Lists", lists_path %>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "Sign in", new_user_session_path %> or
            <%= link_to "Sign up", new_user_registration_path %>
          <% end %>
        </div>

      </div>
    </div>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>


  </div>
</body>
</html>

app/views/lists/edit.html.erb
<h1>Edit List</h1>

<div class="row">
  <div class="col-md-4 col-md-offset-2">
    <%= form_for @list do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/index.html.erb
<% if current_user.present? %>
  <h1>My Lists</h1>

  <div class="row">
    <div class="col-md-5 col-md-offset-1">
      <% @lists.each do |list| %>
        <div class="media">
          <div class="media-body">
            <h4 class="media-heading">
              <%= link_to list.title, list %>
            </h4>
            <p><%= list.description %></p>
          </div>
        </div>
      <% end %>
    </div>

    <div class="col-md-4 col-md-offset-2">
      <%= link_to "New List", new_list_path, class: 'btn btn-success' %>
    </div>

  </div>
<% else %>
  <% flash[:error] = "Please log in or sign up." %>
<% end %>

app/views/lists/new.html.erb
<h1>New List</h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= form_for @list do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/show.html.erb
<h1><%= @list.title %></h1>
<p class="list-description"><%= @list.description %></p>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="media">
      <div class="list-buttons">
        <%= link_to "Edit List", edit_list_path(@list), class: 'btn btn-success' %>
        <%= link_to "Delete List", @list, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this list?' } %>
      </div>
      <div class="media-body">
        <%= render 'items/form' %>
        <table class="table table-bordered table-hover">
          <thead>
            <tr>
              <th>Task</th>
              <th>Days Left</th>
              <th>Mark Complete</th>
            </tr>
          </thead>
          <tbody>
            <%= render partial: 'items/item', collection: @items %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>